# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  build:
    working_directory: ~/vscode-rush
    docker:
      - image: node:16-buster
    steps:
      - checkout
      - run:
        name: "Install dependencies"
        command: |
          npm ci
          npm version $major.$minor.$patch
      - run:
        name: "Building Extension"
        command: |
          npm run build
      - run:
        name: "Executing Unit Tests"
        command: |
          npm run test
      - run:
        name: "Packaging Extension"
        command: |
          mkdir -p ~/vscode-rush/dist &&
          vsce package -o ~/vscode-rush/dist
      - run:
        name: "Publishing Extension"
        command: |
          vsce publish



